### ISSUE TITLE
Question: Is it possible to trigger animation on hover?

### ISSUE THREAD

**Issue by Tosken1337** [daneden/animate.css#863] opened 2018-09-13 13:26 UTC
Question: Is it possible to trigger animation on hover?

Thanks

**Comment by eltonmesquita** [comment] 2018-09-14 22:29
Yeah, of course. Jus use the keyframe names in your CSS instead of the classes directly in your HTML. Something like:
```css
.element:hover {
  animation: jackInTheBox 2s;
}

**Comment by eltonmesquita** [comment] 2018-09-17 22:13
@Tosken1337, any news if that worked? I'm closing this soon if I get no response.

**Comment by max-favilli** [comment] 2018-09-18 09:50
I had the same question.

Seems it works, as long as the element is a block or inline-block element. Doesn't work if it's an inline element. 

Maybe it's intended.

It works.

**Comment by bondt** [comment] 2018-09-18 21:05
Duplicate of #170

**Closed** 2018-09-18 21:37 UTC
