### ISSUE TITLE
Animate.css don't work in Vue.

### ISSUE THREAD

**Issue by iLegion** [daneden/animate.css#993] opened 2019-11-14 08:17 UTC
Vue CLI 4.0.5

The library has stopped working with Vue since version 3.5.2 (CDN).
In the npm version, 3.5.2 does not work either.

**Comment by lianulloa** [comment] 2019-11-15 09:54
Same here.
For me, it throws these error on the console

Refused to apply style from 'http://localhost:8080/animate.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by WarenGonzaga** [comment] 2019-11-28 00:22
Hello guys! We will check this issue and get back to you... can you guys give us steps to replicate it?

**Comment by iLegion** [comment] 2019-11-28 10:37
> Hello guys! We will check this issue and get back to you... can you guys give us steps to replicate it?

Hi, OK. I installing library via npm: `npm install animate.css --save`;
Import this in main.js: `import 'animate.css';`
And adding classes to element: `animated infinite bounce delay-2s`.
In DevTools I see styles but not effects.
Same problems with CDN versions since 3.7.0.
Version 3.6.2 work is good. I think problem in `animation-name`,but it is not exactly.

**Comment by beijinaqie** [comment] 2019-11-29 08:52
> > Hello guys! We will check this issue and get back to you... can you guys give us steps to replicate it?
> 
> Hi, OK. I installing library via npm: `npm install animate.css --save`;
> Import this in main.js: `import 'animate.css';`
> And adding classes to element: `animated infinite bounce delay-2s`.
> In DevTools I see styles but not effects.
> Same problems with CDN versions since 3.7.0.
> Version 3.6.2 work is good. I think problem in `animation-name`,but it is not exactly.

Hi. You can try to write it according to the official vue documentation. Address: https://cn.vuejs.org/v2/guide/transitions.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%87%E6%B8%A1%E7%9A%84%E7%B1%BB%E5%90%8D

**Comment by ddzy** [comment] 2019-12-04 03:20
Same issue:

- vue-cli@4.1.0
- animate.css@3.7.2

**Comment by WarenGonzaga** [comment] 2019-12-06 02:11
Alright, it looks like this is a real issue with animate.css I will work on this... I personally don't use or have experience with vue but I will try to help so we can avoid these issues in the next version of animate.css

**Comment by eltonmesquita** [comment] 2019-12-07 14:31
I just tested on the latest `vue-cli` (4.1.1) and `animate.css` (3.7.2) versions and it works flawlessly. I tried importing it directly into the project and loading through the CDN.
My snippets:
**On CDN**
```html
<template>
  <div id="app">
    <link href="https://cdn.jsdelivr.net/npm/animate.css@3.7.2" rel="stylesheet" type="text/css">
    <img class="animated bounce" alt="Vue logo" src="./assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>
```
**Importing**
```html
<template>
  <div id="app">
    <img class="animated bounce" alt="Vue logo" src="./assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'
import 'animate.css'

export default {
  name: 'app',
  components: {
    HelloWorld
  }
}
</script>
```

Sorry but I think you have some sort of typo or misconfiguration in your project. Please check again your project.

I'll close this issue if I've got no proper answer with some real examples. If you need help using Vue/Webpack and/or animate, please use Stackoverflow or other platforms as this is an issue tracker and you'll won't get much help here about usage.

**Comment by ddzy** [comment] 2019-12-08 03:57
> I just tested on the latest `vue-cli` (4.1.1) and `animate.css` (3.7.2) versions and it works flawlessly. I tried importing it directly into the project and loading through the CDN.
> My snippets:
> **On CDN**
> 
> ```
> <template>
>   <div id="app">
>     <link href="https://cdn.jsdelivr.net/npm/animate.css@3.7.2" rel="stylesheet" type="text/css">
>     <img class="animated bounce" alt="Vue logo" src="./assets/logo.png">
>     <HelloWorld msg="Welcome to Your Vue.js App"/>
>   </div>
> </template>
> ```
> 
> **Importing**
> 
> ```
> <template>
>   <div id="app">
>     <img class="animated bounce" alt="Vue logo" src="./assets/logo.png">
>     <HelloWorld msg="Welcome to Your Vue.js App"/>
>   </div>
> </template>
> 
> <script>
> import HelloWorld from './components/HelloWorld.vue'
> import 'animate.css'
> 
> export default {
>   name: 'app',
>   components: {
>     HelloWorld
>   }
> }
> </script>
> ```
> 
> Sorry but I think you have some sort of typo or misconfiguration in your project. Please check again your project.
> 
> I'll close this issue if I've got no proper answer with some real examples. If you need help using Vue/Webpack and/or animate, please use Stackoverflow or other platforms as this is an issue tracker and you'll won't get much help here about usage.

I was using it by yarn module, but it does not work:

### installing

```bash
yarn add animate.css
```

### importing

```js
<temlate>

<template>
<script>
import Vue from 'vue';
import AnimateCSS from 'animate.css';

Vue.use(AnimateCSS);
</script>
```

**Comment by eltonmesquita** [comment] 2019-12-08 13:36
You're using it as a JavaScript library but animate.css is a pure plain CSS library and should be used as I showed before or it won't work.

There's no official version for any JavaScript library/framework as of today, you just use it as it is, with press CSS. Maybe you were using a non official animate library built for Vue, but you won't get any help here about this.

**Comment by WarenGonzaga** [comment] 2019-12-08 19:18
Maybe you can use this?
https://github.com/asika32764/vue2-animate

**Comment by iLegion** [comment] 2019-12-11 21:31
I import library in scss: `import 'animate.css'`, but it not work.
I add `<link src="/path/to/animate.css"`, is don't work again. It added classes but **not animation**.

**Comment by eltonmesquita** [comment] 2019-12-19 11:30
Sorry, but can you double-check your code and dependencies on the `package.json` file? Also, recheck your webpack configuration if there's any custom settings.
This is certainly a problem with your project and not with vue-cli or even animate.

**Comment by WarenGonzaga** [comment] 2019-12-26 13:38
@eltonmesquita this one is inactive you might considering closing this @eltonmesquita

**Closed** 2019-12-27 00:02 UTC

**Comment by stanleyxu2005** [comment] 2020-03-20 07:49
I can confirm that `yarn add animate.css@3.6.1` works with Vue, but 3.7.x all break with Vue.

**Comment by WarenGonzaga** [comment] 2020-03-20 10:05
We will look into it... @stanleyxu2005

**Comment by skoyah** [comment] 2020-04-15 11:44
latest version works on Vue. I had the same problem until I realise my element, that was a link had no display type. Adding a display of "block", "inline-block" solved my issue.

**Comment by raulcesar** [comment] 2020-05-08 15:39
Hi, I just tried to upgrade to version 4.0.0 and started getting the error "Cannot read property 'prefix' of undefined" with a vue-cli project.

in my main.js file, I had this:
`import 'animate.css/animate.min.css';`
Which worked with animate version 3.7.2, but when I upgraded to 4.0.0, I get the error "cannot read property 'prefix' of undefined".
Tried to change the import to: `import 'animate.css';`, but this had no effect.

Any ideas?

**Comment by WarenGonzaga** [comment] 2020-05-08 15:47
@raulcesar please refer to our official documentation ;)
[https://animate.style/#migration](https://animate.style/#migration)

**Comment by raulcesar** [comment] 2020-05-11 13:48
@WarenGonzaga Thanks for the reply, but unfortunately this alone did not work for me. 
I forgot to mention in my original post, but I had already tried following the orientations on migration (using the animate.compat.css) but the problem still persisted. I was able to fix it this morning, so I will just comment below the steps I took so that if anyone else is having this problem, this might help. The "tldr;" version of the solution for me was: just upgrade to version 4.1 of animate.css.
Here is the longer explination (just for reference): 

First, I was able to trace the error down to postcss-loader (which I use in my project). 
By removing the file "postcss.config.js" from my project, the error stopped ocurring, so I tried to see if I could reproduce the problem in a brand new project. However, I could not replicate the error, that is, it all worked flawlessly.
After comparing my 2 projects, I noticed that the new one had fetched version 4.1 of animate.css (and the older one was using 4.0), so I upgraded to that version in my original project and that made the error go away.
I also noticed that in the 4.0 version of animate.css, there was a "postcss.config.js" in the modules root directory, but in 4.1 this file is no more. 
Also, just as a test, I "downgraded" the new project to 4.0 and sure enough, the error appeared. 
Anyway, since the problem went away with 4.1 version, I stopped debugging.

Don't know if this was just a coincidental thing, but either way, thanks for the upgrade!

**Comment by WarenGonzaga** [comment] 2020-05-11 14:06
@raulcesar awesome! I can't answer your question since I'm not the one who implemented that it is @eltonmesquita he can answer your question related to vue... also I don't have experience yet with vue but there are some vue animate.css repos out there you can check out.

**Comment by eltonmesquita** [comment] 2020-05-11 14:15
It seems that when a css library provides a postcss config file some bundlers use it, like parcel, but they breaks if we export a function and not an object, which we do for Animate.css.

I don't fully understand why they blunders act like this, but it seemed plausible to not distribute the library with it the config file. That's why the new release only packs the CSS files.

**Comment by cloydlau** [comment] 2020-05-16 08:50
3.7.2 works perfectly in my case, but 4.1.0 doesn't. I'm using vue-cli 4.3.1.

**Comment by eltonmesquita** [comment] 2020-05-16 11:43
I just tried and it worked flawlessly with both `animate.css` and `animate.compat.css`.

Please read the [migration guide](https://animate.style/#migration).

**Comment by cloydlau** [comment] 2020-05-16 12:44
yeah adding prefix should do it, thanks.

**Comment by nufrankz** [comment] 2020-07-12 11:50
On Node.js, just import the static CSS into your SASS main file without the ".css" extension, and it should work. Don't know if in Vue.js is the same or not, give it a try.

**Comment by FatimaMazhit** [comment] 2021-06-10 12:30
I just tried it with animate.css@4.1.1 it didn't work. Then i switched to vue docs cdn version it worked and right now it's working in vue: 
animate.css@3.5.1
vue@2.6.14
in app.js:
import "animate.css/animate.css";

**Comment by fm3o5** [comment] 2021-06-17 21:34
> > I just tested on the latest `vue-cli` (4.1.1) and `animate.css` (3.7.2) versions and it works flawlessly. I tried importing it directly into the project and loading through the CDN.
> > My snippets:
> > **On CDN**
> > ```
> > <template>
> >   <div id="app">
> >     <link href="https://cdn.jsdelivr.net/npm/animate.css@3.7.2" rel="stylesheet" type="text/css">
> >     <img class="animated bounce" alt="Vue logo" src="./assets/logo.png">
> >     <HelloWorld msg="Welcome to Your Vue.js App"/>
> >   </div>
> > </template>
> > ```
> > 
> > 
> > **Importing**
> > ```
> > <template>
> >   <div id="app">
> >     <img class="animated bounce" alt="Vue logo" src="./assets/logo.png">
> >     <HelloWorld msg="Welcome to Your Vue.js App"/>
> >   </div>
> > </template>
> > 
> > <script>
> > import HelloWorld from './components/HelloWorld.vue'
> > import 'animate.css'
> > 
> > export default {
> >   name: 'app',
> >   components: {
> >     HelloWorld
> >   }
> > }
> > </script>
> > ```
> > 
> > 
> > Sorry but I think you have some sort of typo or misconfiguration in your project. Please check again your project.
> > I'll close this issue if I've got no proper answer with some real examples. If you need help using Vue/Webpack and/or animate, please use Stackoverflow or other platforms as this is an issue tracker and you'll won't get much help here about usage.
> 
> I was using it by yarn module, but it does not work:
> 
> ### installing
> ```shell
> yarn add animate.css
> ```
> 
> ### importing
> ```js
> // main.js
> import Vue from 'vue';
> import AnimateCSS from 'animate.css';
> 
> Vue.use(AnimateCSS);
> ```

This seems to solve my issue before it was like this

`import './assets/css/animate.min.css';` in `main.js`

Now I have removed this and added these lines.
`import AnimateCSS from 'animate.css';` and `Vue.use(AnimateCSS);`

**Comment by WarenGonzaga** [comment] 2021-06-18 05:12
Hi, @eltonmesquita I guess it is worth pinning this issue on our issue tracker?

**Comment by saqibfarooq1992** [comment] 2022-05-05 11:44
> I can confirm that `yarn add animate.css@3.6.1` works with Vue, but 3.7.x all break with Vue.

great

**Comment by Mohammed-Ziyad** [comment] 2024-05-12 15:32
I have made many attempts with wow js and this method did not work. After many attempts, I tried a different method, and I hope it works for you correctly

I downloaded the library from https://github.com/graingert/wow Then I copied these files 1- animate.css 2- wow.min.js
Then I included the two files in my project
In the main.js file I wrote

import "./assets/css/animate.css";
import WOW from "./assets/js/wow.min.js";

//  Wow.js
const wow = new WOW();
wow.init();
