### ISSUE TITLE
Animations makes bootstrap modals see-through

### ISSUE THREAD

**Issue by omdawe** [daneden/animate.css#996] opened 2019-11-29 07:57 UTC
I just had a client here that was using a iphone and all the animations for modals made them see-through. You can still interact with the menus but as you only see lets say 5% of the modal you can not interact with them.

**Comment by WarenGonzaga** [comment] 2019-12-06 02:12
Can you replicate this issue so we can debug it pretty easily? You can use something like codepen.io

**Comment by omdawe** [comment] 2019-12-06 09:56
Nope.. I do not have a iphone.. But if you got one i can setup a test site to show you the problem.

**Comment by omdawe** [comment] 2019-12-06 10:03
https://jsfiddle.net/user1296114/t30feuac/ I can not test it if it works or not as i do not have a iphone but i seen it with my own eyes on a clients phone!

**Comment by eltonmesquita** [comment] 2019-12-07 14:39
Can you provide the iOS version? There are so many bugs related to Safari that it can be caused by a particular version ofSafari.

**Comment by omdawe** [comment] 2019-12-09 20:04
13.2.3 IOS my dad got!

**Comment by WarenGonzaga** [comment] 2019-12-26 13:37
@omdawe alright... let's wait for @eltonmesquita

**Comment by eltonmesquita** [comment] 2020-03-01 17:31
Sorry, but I couldn't replicate the issue. This is probably a Safari bug which wouldn't make sense to try and fix through some nasty hack.
I'll close this and if there are more reports about this in the future I'll worry about.
Thanks for reporting!

**Closed by eltonmesquita** 2020-03-01 17:31 UTC
