### ISSUE TITLE
Animate elements one by one?

### ISSUE THREAD

**Issue by Aaarrrgggh** [daneden/animate.css#946] opened 2019-06-12 15:21 UTC
Hi all,

I would like to know if it's possible to animate elements one by one. For example, list elements, one after one, with a delay?

Thanks,

Alexander

**Comment by KasimAhmic** [comment] 2019-06-13 12:58
To my knowledge, there isn't any way of doing this in animate.css alone. You're going to have to use JavaScript to apply an increasing delay to each element you're trying to animate. Something like the following should work for a simple grouping of elements with the same class:

```javascript
document.querySelectorAll('.selector').forEach((element, index) => {
    element.classList.add('animated', 'slideInLeft', 'delay-' + index + 's');
});
```
[Live CodePen Example](https://codepen.io/anon/pen/KjpOqG)

If you have completely different elements, you can create a function that stores them in an array and then iterates over that array applying an increasing animation delay to each element.

Note that the code example given above is using the default delay classes that come with animate.css. You can add your own class using the `animation-delay` property in CSS if you need different timings.

Hope this answered your question!

**Comment by holypolarpanda7** [comment] 2019-06-16 20:19
Hello,

I believe you may also use the animation stop (described on the github
page) event via javaScript to assist in creating this effect.

Greg Wagner

**Comment by Aaarrrgggh** [comment] 2019-06-17 09:15
Okay thank you @KasimAhmic! I did not know the delay-x class supported by animate.css.

**Comment by eltonmesquita** [comment] 2019-06-17 11:42
As the issue is solved, I'm closing it.

**Closed by eltonmesquita** 2019-06-17 11:42 UTC
