### ISSUE TITLE
CDNJS - wrong content

### ISSUE THREAD

**Issue by vejin** [daneden/animate.css#735] opened 2017-09-03 12:23 UTC
Noticed after trying to use 'jackInTheBox', added in v3.5.2, that CDN version for v3.5.2 is actually v3.5.1. See here:
https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css

It's not just wrong version number, it is v3.5.1 (missing new features).

**Comment by clebersa** [comment] 2017-09-27 19:44
I just checked it and it seems like this has been happening since v3.5.0:

- https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.css points to v3.5.1
- https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.1/animate.css points to v3.5.0
- https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.0/animate.css points to v3.5.0 (match)

**Comment by eltonmesquita** [comment] 2017-12-10 02:44
Yeah... This seems to be caused by a bump of a version. I think this will get fixed in the next release.

**Comment by pjotrsavitski** [comment] 2018-03-09 16:06
Any chance of new versions getting tagged? It seems that no new releases have been tagged.

**Comment by eltonmesquita** [comment] 2018-03-14 02:53
I'll try to have a look at it on this week. I'm still getting used to how CDN publishing works...

**Comment by DSpeichert** [comment] 2018-06-04 05:47
@eltonmesquita It would be helpful if you could "tag a release" here on GitHub. The tag name should correspond to the version in package.json or else a content mismatch will happen.

**Comment by daneden** [comment] 2018-07-21 14:41
The latest tag should have fixed this issue 🤞

**Closed by daneden** 2018-07-21 14:41 UTC
Labels: bug
