### ISSUE TITLE
Making an SVG circle bounce in properly

### ISSUE THREAD

**Issue by SandiDusic** [daneden/animate.css#806] opened 2018-04-08 15:59 UTC
```
<html>
<head>
    <link rel="stylesheet" type="text/css" href="animate.css">
</head>
<body>
    <svg width="1366px" height="700px">
        <g transform="translate(0 0)">
            <g class="animated bounceIn">
                <circle style="background-color: red" cx="500px" cy="200px" r="60px" fill="rgba(255, 255, 255, 1)" stroke="rgba(94, 129, 193, 1)" stroke-width="7px"></circle>
            </g>
        </g>
    </svg>
</body>
</html>
```
![peek 2018-04-08 17-54](https://user-images.githubusercontent.com/1926491/38469502-234e3ff6-3b56-11e8-9473-51a78195e77a.gif)

As you can see, the circle doesn't start bouncing in from its center, but from a top left position. It doesn't just expand radially, but also translates along the diagonal.  The farther away from the top left corner the circle is, the more it stretches in animation. The behavior is the same when the class is assigned to the surrounding `g` or directly to `circle`. How can I get a nice centered bounce like with HTML elements?

**Comment by WarenGonzaga** [comment] 2018-04-12 20:28
Hello I think you having an issue because you improperly place the css inside the g element. Try this one..

```html
<html>
<head>
    <link rel="stylesheet" type="text/css" href="animate.css">
</head>
<body>
    <div class="animated bounceIn">
    <svg width="1366px" height="700px">
        <g transform="translate(0 0)">
                <circle style="background-color: red" cx="500px" cy="200px" r="60px" fill="rgba(255, 255, 255, 1)" stroke="rgba(94, 129, 193, 1)" stroke-width="7px"></circle>
        </g>
    </svg>
    </div>
</body>
</html>
```

and also can you please provide a codepen.io link for this issue so we can easily debug the problem. Thanks!

**Comment by SandiDusic** [comment] 2018-04-12 22:16
Here's a codepen: https://codepen.io/anon/pen/EEzPBJ

Your solution is inconvenient because it requires me to wrap all my circles in `div`s and then embed them in SVG again. This is doable, but I've read these classes should work on SVG nodes as well.

**Comment by eltonmesquita** [comment] 2018-04-16 12:05
The problem is that there are some nasty bugs with SVG transforms (mainly transform origin related) in several browsers. When 3D transforms are used the problems usually get worse. And yes, animate.css does use 3D transforms.
There isn't a quick fix it or hack for this. If you're animating SVGs a lot, you should probably consider a js animation library like gsock that deals with the bugs in several browsers. Unfortunately animate the outer SVG element is one of the few ways to avoid some bugs.

**Comment by WarenGonzaga** [comment] 2018-04-16 12:38
@eltonmesquita yeah, that's what I am talking about... put the animate.css outer above the SVG elements so that the animation will work. So yeah indeed in SVG plus Greensock animation. GSAP can perfectly handle the SVG to use with different browsers. Better to check it out here --> https://greensock.com/svg-tips also if you have some question regarding GSAP you can mention there I am also a contributor to GSAP. tag me as @WarenGonzaga thanks...

**Comment by SandiDusic** [comment] 2018-04-16 22:08
@eltonmesquita  Okay, thank you. Maybe this would be useful to point out somewhere in the README?

As far as I'm concerned, this issue can be closed.

**Comment by eltonmesquita** [comment] 2018-04-17 11:25
Good idea, referring to #681 noting the request 😁
Closing it.

**Closed by eltonmesquita** 2018-04-17 11:25 UTC
