### ISSUE TITLE
scroll to top bug

### ISSUE THREAD

**Issue by sylido** [daneden/animate.css#897] opened 2019-01-10 17:41 UTC
I have the `animated` and `fadeInRight` to a wrapper div that basically holds the whole page. Clicking on a `slickgrid` row of a grid I have on the page for some reason moves the whole page to the top, where the wrapper is. I do have some bootstrap 3 modal boxes too. Removing the `fadeInRight` but keeping the `animated` class solves the problem - no scroll to the top is triggered. I do realize this library deals with only CSS, but I think it's somehow interacting with other libraries. Is there any documented stuff that we are not supposed to do to avoid this ? Or are there any ways that one can debug this behavior that you are aware of ?

**Comment by eltonmesquita** [comment] 2019-01-10 18:52
First, don't animate a whole page. That won't be any good for your users, as it just confuses and degrades the performance.
Second, that's just an overflow problem. Put the element inside other one with `overflow: hidden` set and no more scroll bars...

**Comment by sylido** [comment] 2019-01-14 03:07
I think I traced the issue by chance, it seems to relate to how browsers don't focus on elements in some cases. For some reason when the animation runs it goes to the top where the first input element is. Not sure how to stop it, the solution is to focus on some element lower on the page, but open to any suggestions.

**Comment by eltonmesquita** [comment] 2019-01-16 22:51
Sorry, i think I misunderstood it at the first moment. But anyway, it's hard to help without a live code running somewhere. If you can provide this, someone might be able to help.

**Comment by sylido** [comment] 2019-01-17 00:44
No worries @eltonmesquita here is a [codepen example, try clicking on a slickgrid row on the bottom, I immediately get moved to the top of the page.](https://codepen.io/anon/pen/gZyBVL)

**Comment by eltonmesquita** [comment] 2019-01-25 13:52
Yeah, this is some of those really nasty bug which you'd probably have to debug the library you're using to find the cause. I don't think animate is to be blamed here as we just add animations to specified elements and nothing more. It should never mess with scroll position.

Did you consider to try other library as slickgrids is massively outdated?

**Comment by sylido** [comment] 2019-01-25 16:18
I mean removing the .fadeInRight class fixes the issue, you can try it on the codepen, so it seems like it is somehow related. Maybe it's a general animation/browser issue, so I was just wondering if there are any known interactions between jquery/jquery-ui/the other libraries I've added to the codepen and animate.css. As far as slickgrid, we are using a highly customized version of it, maybe I'll try the slickgrid fork to see if the problem is present there. Thanks for looking at it @eltonmesquita, feel free to close it if it's unrelated.

**Comment by eltonmesquita** [comment] 2019-02-09 17:34
> I mean removing the .fadeInRight class fixes the issue, you can try it on the codepen, so it seems like it is somehow related. Maybe it's a general animation/browser issue, so I was just wondering if there are any known interactions between jquery/jquery-ui/the other libraries I've added to the codepen and animate.css. As far as slickgrid, we are using a highly customized version of it, maybe I'll try the slickgrid fork to see if the problem is present there. Thanks for looking at it @eltonmesquita, feel free to close it if it's unrelated.

Sorry, but I can't help much here as I'd have to debug the whole slickgrid library to find the issue and that's just not feasible. In theory a css animation would never mess with interactions or even with the page scroll but I've seen enough bizarre bugs happening in a browser to say that's impossible.

Still, I think that using an outdated is hardly a good idea. My advise stands: it's better to look for an alternative library, or even create your own than using such and outdated library as slickgrid.

**Comment by gt0p** [comment] 2019-02-26 10:51
> @sylido this is strange, I'll look into this. Despite that it's not recommended to do animation on body in my opinion.
> 
> What I see right now is that it's working properly when you remove `animation-fill-mode: both;` from `.animated` selector. (or if you set it to `backwards`)

I have a similar use case in which your proposal works.
Problem: A container (aka parent element) has the animation fadeIn and a inner button element triggers a dropdown menu which is *not* overflow its parent as it used to do.
 
As far as I know when we define `animation-fill-mode: forwards|both;`, we are telling the browser that we want our animated element to hold on to its final set of styles, as defined in the last keyframe. In my case I use fadeIn which plays with the opacity property.

Opacity is irrelevant with overflow/z-index stuff, so :/

Here is a similar issue which maybe will be somehow helpful for you, it didn't work for me.
https://stackoverflow.com/questions/26099421/css-animation-fill-mode-and-z-index-issue/26099518?noredirect=1#comment40900317_26099518

**Comment by sylido** [comment] 2019-02-26 22:32
thanks @max-ci your suggestion does fix the issue - I wonder what exactly the "forwards" triggers that "backwards" only doesn't - seems like a weird browser animation interaction, there might be a bug there.

@eltonmesquita you can easily try doing what I suggested to the codepen example you wanted me to provide to be completely convinced that what me and @max-ci are observing in this case is 100% happening. I wouldn't even suggest you debug slickgrid, I only asked about the plugins which slickgrid uses - basic building blocks of the web like jquery and jquery-ui. Either way thanks for looking at it, I might just leave this issue open since others like @gt0p seem to be having similar unexplained issues, albeit a bit different.

**Comment by eltonmesquita** [comment] 2019-03-19 19:30
Sorry I didn't make myself clear, but after you provided the example I saw with my own eyes that the bug exist.  The problem is that this is too bloated to have a proper answer to what's the problem there.
There's no known problem with any library like jQuery, jQuery UI or any other js library as we're just adding some animations to some elements.
As this isn't an issue with animate.css itself and there's a fix already for this, I think it's fair enough to close this issue, right?
Thanks for reporting the issue!

**Closed** 2019-03-19 19:30 UTC
Labels: wontfix
