### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by ZLHysong** [daneden/animate.css#641] opened 2016-10-07 15:06 UTC
Chrome Console gives this error when reloading any page in my project that contains this file.

I says it is on line 1:  `@charset "UTF-8";`

**Comment by dotamir** [comment] 2016-10-24 12:41
just in the Chrome console ?

**Comment by ZLHysong** [comment] 2016-11-02 12:00
So far as I know, yes. Nothing appears different on screen.

**Comment by eltonmesquita** [comment] 2017-03-09 02:07
Not an issue, just some specific and isolated Chrome's behavior.
Closing this.

**Closed by eltonmesquita** 2017-03-09 02:07 UTC

**Comment by yanickrochon** [comment] 2018-05-03 19:04
What do you mean "Not an issue"? How can this be resolved?

**Comment by eltonmesquita** [comment] 2018-05-04 13:15
This isn't something related to the project itself. As far as I can remember, one single version of Chrome was throwing this error without a real reason but it didn't break anything. Also 99% of the cases this kind of error happens is not animate.css' fault as it's just CSS and that's usually related to Javascript code.

**Comment by unclespode** [comment] 2018-06-29 19:51
I had this issue, ended up here via Google. It turned out I had tried to load the CSS file as a JavaScript file - i.e user error. Might help someone else.

**Comment by soccerKevin** [comment] 2018-08-17 18:36
I can confirm that this error is caused by trying to load css as a script tag

**Comment by Lahirutech** [comment] 2019-01-18 15:03
> I can confirm that this error is caused by trying to load css as a script tag

Solved it

**Comment by OC-Dev** [comment] 2020-03-30 12:21
> I can confirm that this error is caused by trying to load css as a script tag

Sometimes it's the real simple things when you're just tired or not really in the mood - Can't believe I was trying to load in a CSS file under a Script tag...
