### ISSUE TITLE
Really choppy animations in Chrome iOS

### ISSUE THREAD

**Issue by terryupton** [daneden/animate.css#934] opened 2019-05-09 11:35 UTC
Has anyone else noticed really choppy animations in Chrome on IOS?
Seems fine in Safari on IOS and Chrome Desktop.

Any ideas as to what might be causing this?

**Comment by WarenGonzaga** [comment] 2019-05-09 19:37
Can you provide a video or gif of being choppy of animations? What I think is, it cause by this issue #928

**Comment by sivot** [comment] 2019-05-10 06:08
Tested on 300+ ipad 4, air, air 2, pro. :) Really. IOS 10/11/12. There is no problem. Chrome not tested, just Safari and Standalone Web Application. Look like the problem is in your device/settings/webapp.
If you want to use large and/or complex animations you need to understand the "new" Webkit render engine... Google is your friend...

**Comment by terryupton** [comment] 2019-05-10 07:17
@sivot - yes there is no issue on any Safari, it is Chrome that is the problem as stated in the title. 
As for complex animations - not really!? All I am doing is using the simple fadeInDown with a delay for each child item, so I wouldn't really call this a complex/large scale animation.

I believe this is either a bug (or an adjustment of code required) as per the related thread [#928](https://github.com/daneden/animate.css/issues/928) that @WarenGonzaga mentioned. Or it is a Chrome bug? But not able to verify this.

@WarenGonzaga please find videos below that show the issue.
One from Chrome (problem) and one from Safari as to how it should and does render correctly.

**Chrome**
https://www.dropbox.com/s/xhu43wvbamynsto/RPReplay_Final1557469240.MP4?dl=0

**Safari (working)**
https://www.dropbox.com/s/xg5pcbl219odman/RPReplay_Final1557469307.MP4?dl=0

**Comment by sivot** [comment] 2019-05-10 08:44
@terryupton Ok. This is not choppy, this is another render engine. You need to learn how to DOM and CSOM works. I think the problem is in your case the DOM manipulation time. Try to do it in one instance. Welcome in the WebDevelopment Funny World...

**Comment by terryupton** [comment] 2019-05-10 08:54
@sivot I have used this technique many time before without issue (it used to work in Chrome iOS). It works everywhere else I have tested except in Chrome on iOS. I don't think i _need_ to learn about the DOM and CSOM in order to implement a simple animation. 

If I did it in once instance, then I would not get the effect of each item sliding in down separately, it would be just a block sliding in and this wouldn't look.

I would describe this as Choppy.

**Choppy**
/ˈtʃɒpi/ _adjective_
_having a disjointed or jerky quality._

So wording aside - it certainly isn't smooth like it should be.

**Comment by WarenGonzaga** [comment] 2019-05-11 04:26
@terryupton what I can see is a bug in chrome... I think we need to create a dummy animation for your issue and put in codepen so everyone can debug and solve it. Are you able to reproduce this issue? Let's use Codepen for debugging.

**Comment by sivot** [comment] 2019-05-11 14:21
@WarenGonzaga 

Reason and Solution here: #932. 

Codepen Tester: https://codepen.io/ericwbailey/pen/PWJPrW

As you can see need to update the css rule with a simple parameter in your library...
`@media (prefers-reduced-motion)` -> `@media (prefers-reduced-motion: reduce)`

Because, with the new Chrome and Firefox update fires the `reduce` option basically if not parameter set.

You can test it on Windows 10:
`Settings` -> `Ease of Access` -> `Show animations in Windows` -> `Turn Off`
The need to reload the page...

**Comment by eltonmesquita** [comment] 2019-05-14 23:49
Alright, I'll close this as it's a duplicate of #928 .

**Closed by eltonmesquita** 2019-05-14 23:49 UTC

**Comment by moander** [comment] 2019-12-05 13:50
I'm experiencing choppy animations on Chrome IOS. Safari and Firefox IOS works as expected. Have this issue been reintroduced?

It's happening both on transitions using `animated` and build-in ones like `<stepper animate>`

Chrome version 78.0.3904.84 IOS 13.2.3

**Comment by WarenGonzaga** [comment] 2019-12-06 12:24
Hi @moander can you replicate your issue in codepen?

**Comment by moander** [comment] 2019-12-06 17:47
@WarenGonzag sorry I thought I was commenting on a quasar issue ;)

https://github.com/quasarframework/quasar/issues/5809
